version: '3'
services:
  db:
    image: mysql:5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'root'
    volumes:
      - /home/gponty/docker/data/mysqlSf:/var/lib/mysql

  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .env:.env